# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
 # fileSystems."/home/jopejoe1/Public/games" = {
 #   device = "/dev/sda";
 #   fsType = "bcachefs";
 #   options = [ "compression=zstd" ];
 # };

  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
